# Generated by Django 4.0.4 on 2022-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(default='Only description', max_length=1000),
        ),
    ]
